# server port setting 
server.port=8088
server.servlet.context-path=/yorijori

# thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.view-names=thymeleaf/*

# JSP 
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

# DB setting
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/yorijori?serverTimeZone=UTC&CharacterEncoding=UTF-8
spring.datasource.username=yorijori
spring.datasource.password=yorijori1234
spring.datasource.hikari.maximum-pool-size=20

# Mybatis
mybatis.mapper-locations=classpath:/mapper/**.xml
mybatis.type-aliases-package=com.yorijori.foodcode

#JPA
spring.jpa.show-sql=true 
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.use_sql_comments=true
#jpa batch size setting
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# log
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace


# log
#logging.level.org.springframework.jdbc=debug
#logging.level.com.zaxxer.hikari=debug

C:/project/upload/
file.dir=/project/upload/

spring.servlet.multipart.maxFileSize=50MB
spring.servlet.multipart.maxRequestSize=50MB

spring.devtools.livereload.enabled=true
